FROM node:12-alpine 
WORKDIR /app/server
COPY ./server/package.json ./server/package-lock.json ./
RUN npm install
COPY server/src ./src
RUN npm run build
RUN npm prune --production # Remove dev dependencies

CMD ["node", "./build/stream-service/app.js"]