FROM node:slim 
WORKDIR /app/react-client
COPY ./react-client/build ./build

WORKDIR /app/server
COPY ./server/package.json ./server/package-lock.json ./
RUN npm install
COPY server/src ./src
RUN npm run build
RUN npm prune --production # Remove dev dependencies

CMD ["node", "./build/sync-worker/worker.js"]